const LogAction = Object.freeze({
  // Champion Actions
  CREATE_CHAMPION: "CREATE_CHAMPION",
  DELETE_CHAMPION: "DELETE_CHAMPION",
  UPDATE_CHAMPION: "UPDATE_CHAMPION",

  // Champion Avatar Actions
  ADD_CHAMPION_AVATAR: "ADD_CHAMPION_AVATAR",
  UPDATE_CHAMPION_AVATAR: "UPDATE_CHAMPION_AVATAR",
  DELETE_CHAMPION_AVATAR: "DELETE_CHAMPION_AVATAR",

  // Champion Quotes Actions
  ADD_CHAMPION_QUOTE: "ADD_CHAMPION_QUOTE",
  UPDATE_CHAMPION_QUOTE: "UPDATE_CHAMPION_QUOTE",
  DELETE_CHAMPION_QUOTE: "DELETE_CHAMPION_QUOTE",

  // Champion Photos Actions
  ADD_CHAMPION_PHOTO: "ADD_CHAMPION_PHOTO",
  UPDATE_CHAMPION_PHOTO: "UPDATE_CHAMPION_PHOTO",
  DELETE_CHAMPION_PHOTO: "DELETE_CHAMPION_PHOTO",

  // Region Actions
  CREATE_REGION: "CREATE_REGION",
  DELETE_REGION: "DELETE_REGION",
  UPDATE_REGION: "UPDATE_REGION",

  // Region Stories Actions
  CREATE_REGION_STORY: "CREATE_REGION_STORY",
  UPDATE_REGION_STORY: "UPDATE_REGION_STORY",
  DELETE_REGION_STORY: "DELETE_REGION_STORY",

  // Region Photos Actions
  ADD_REGION_PHOTO: "ADD_REGION_PHOTO",
  UPDATE_REGION_PHOTO: "UPDATE_REGION_PHOTO",
  DELETE_REGION_PHOTO: "DELETE_REGION_PHOTO",

  // Race Actions
  CREATE_RACE: "CREATE_RACE",
  DELETE_RACE: "DELETE_RACE",
  UPDATE_RACE: "UPDATE_RACE",

  // Race Stories Actions
  CREATE_RACE_STORY: "CREATE_RACE_STORY",
  UPDATE_RACE_STORY: "UPDATE_RACE_STORY",
  DELETE_RACE_STORY: "DELETE_RACE_STORY",

  // Race Photos Actions
  ADD_RACE_PHOTO: "ADD_RACE_PHOTO",
  UPDATE_RACE_PHOTO: "UPDATE_RACE_PHOTO",
  DELETE_RACE_PHOTO: "DELETE_RACE_PHOTO",

  // Faction Actions
  CREATE_FACTION: "CREATE_FACTION",
  DELETE_FACTION: "DELETE_FACTION",
  UPDATE_FACTION: "UPDATE_FACTION",

  // Faction Stories Actions
  CREATE_FACTION_STORY: "CREATE_FACTION_STORY",
  UPDATE_FACTION_STORY: "UPDATE_FACTION_STORY",
  DELETE_FACTION_STORY: "DELETE_FACTION_STORY",

  // Faction Photos Actions
  ADD_FACTION_PHOTO: "ADD_FACTION_PHOTO",
  UPDATE_FACTION_PHOTO: "UPDATE_FACTION_PHOTO",
  DELETE_FACTION_PHOTO: "DELETE_FACTION_PHOTO",

  // Translation Actions
  ADD_TRANSLATION: "ADD_TRANSLATION",
  UPDATE_TRANSLATION: "UPDATE_TRANSLATION",
  DELETE_TRANSLATION: "DELETE_TRANSLATION",

  // General Stories Actions
  CREATE_MAIN_STORY: "CREATE_MAIN_STORY",
  UPDATE_MAIN_STORY: "UPDATE_MAIN_STORY",
  DELETE_MAIN_STORY: "DELETE_MAIN_STORY",

  CREATE_SIDE_STORY: "CREATE_SIDE_STORY",
  UPDATE_SIDE_STORY: "UPDATE_SIDE_STORY",
  DELETE_SIDE_STORY: "DELETE_SIDE_STORY",

  // Relationship Management
  LINK_CHAMPION_TO_REGION: "LINK_CHAMPION_TO_REGION",
  UNLINK_CHAMPION_FROM_REGION: "UNLINK_CHAMPION_FROM_REGION",
  LINK_RACE_TO_REGION: "LINK_RACE_TO_REGION",
  UNLINK_RACE_FROM_REGION: "UNLINK_RACE_FROM_REGION",

  // Other General Actions
  BACKUP_DATA: "BACKUP_DATA",
  RESTORE_DATA: "RESTORE_DATA",
  SYSTEM_MAINTENANCE: "SYSTEM_MAINTENANCE",
  DATA_MIGRATION: "DATA_MIGRATION",
});

module.exports = LogAction;
